### ISSUE TITLE
[epic] New codegen annotation

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-javascript-sdk#235]
- [x] add new annotations in SDK project #230
- [ ] add more tests that verifies codegen is producing value code
- [ ] adapt documentation
- [ ] samples
- [ ] adapt TCK tests in the SDK
- [ ] adapt quickstarts
