### ISSUE TITLE
[epic] Bring in npm-js and javascript codegen

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-javascript-sdk#30]
As discussed, we plan to merge into this project the npm-js and the javascript codegen. 

The execution plan is as follow: 

## Phase 1:

- [ ] **move**: bring `npm-js` under `javascript-sdk` (preserving commit history)
- [ ] **build**: must be integrated in CircleCI (similar to what we are doing to the samples already)
- [ ] **versioning**: we want the `npm-js` to have the same version of the `javascript-sdk`. 
- [ ] **publishing**: `npm-js` artifact must be published under a new name because of version misalignment 
- [ ] **docs**: documentation must be adapted since we will have a new artifact name
- [ ] **github issues**: move all open issues from `npm-js` to `javascript-sdk`

## Phase 2:

First we need to split codegen into codegen-core, codegen-java and codegen-js (preserving commit history) See https://github.com/lightbend/akkaserverless-codegen/issues/147

- [ ] move `codegen-js` under `javascript-sdk` (preserving commit history)

Please, feel free to add here any other point of action that you believe we will need.

**Comment by octonato** [comment]
To merge a project preserving the history, we should do the following:

How to merge a git repo (foo) into a repo (bar):

* **foo**: move the contents of the repo into a directory (make sure that includes any dot files, such as .gitignore, but then make sure you don't nest the .git directory)
* **foo**: remove whatever you don't want to merge in bar (eg. CI build files)
* **foo**: commit locally
* **foo**: optional - remove issues and PR references from commit messages
  * needs git-filter-repo
  * run `git-filter-repo --message-callback 'return re.sub(b" \(#\d+\)", b"", message)'`
  * run `git-filter-repo --message-callback 'return re.sub(b"#\d+", b"#XXX", message)'`
* **bar**: add foo as a remote - use path in your file system, you don't need to push the changes to foo origin
* **bar**: fetch the branch in foo remote you want to merge
* **bar**: git merge --allow-unrelated-histories foo/branch

Credits to @dwijnand for the git fu and to @pvlugter for the `git-filter-repo` trick.

**Comment by pvlugter** [comment]
I think this is all done and can be closed now.
